### ISSUE TITLE
Incompatibility with Farmers Delight

### ISSUE THREAD

**Issue by deltaminimal** [pufmat/attributesmod#9] opened 2024-10-27 21:20 UTC
The last update causes a crash at launch when both mods are installed, rolling back to the previous version solves the issue.

**Comment by BigMartin58** [comment] 2024-10-28 04:04
Idk if this is related but I am also [crashing](https://api.mclo.gs/1/raw/xhvaxG1) on launch. No crash logs, just exits. Since my log doesn't say anything about Farmer's Delight, I will also make a separate thread.

**Comment by pufmat** [comment] 2024-10-28 10:10
> The last update causes a crash at launch when both mods are installed, rolling back to the previous version solves the issue.

Please send the crash report and specify version of the game and mods.

**Comment by deltaminimal** [comment] 2024-10-28 14:03
Minecraft 1.20.1, Farmers Delight 1.2.4, pufferfish atributes 0.6.0
[crash-2024-10-28_11.00.55-fml.txt](https://github.com/user-attachments/files/17543568/crash-2024-10-28_11.00.55-fml.txt)

If you need me to test something, disable a mod, etc, let me know.

**Comment by pufmat** [comment] 2024-10-28 19:49
I think the incompatibility is not caused by Farmers Delight. Please disable it and test again.

**Comment by deltaminimal** [comment] 2024-10-29 03:56
Sorry for the delay, I disabled Farmers Delight, and the other delight's addons (aether's delight, aquaculture delight, sunflower delight, naturalist delight and packedup) and the game launches normally.

**Comment by pufmat** [comment] 2024-10-30 14:52
Okay, in that case incompatibility is probably caused by one of the addons. Please enable just Farmers Delight without any addons.

**Comment by deltaminimal** [comment] 2024-10-30 16:30
With only Farmers Delight enabled it still crashes. No addons enabled.

**Comment by pufmat** [comment] 2024-10-31 14:17
This is not good, it means that the conflict between more than two mods. However, I found out that the error you get is also a result of a [mixin bug](https://github.com/SpongePowered/Mixin/issues/544), and now I know how to fix the issue.

**Comment by deltaminimal** [comment] 2024-10-31 14:20
Great! Let me know if there´s anything else I can do, if you want I can create an instance with only the two mods to see what happens

**Comment by pufmat** [comment] 2024-11-04 21:21
Please test if the issue is fixed in version 0.6.1 of Pufferfish's Attributes mod.

**Comment by deltaminimal** [comment] 2024-11-04 21:57
It works! You are awesome!

**Closed as completed** 2024-11-05 12:06 UTC
